Update zlib to the version from component registry
Under esp-idf 6.0, compiler is called with -Werror=old-style-definition,
and old k&r zlib does not compile:

.../LilyGo-EPD47/src/zlib/deflate.c:1482:12: error: old-style function definition [-Werror=old-style-definition]
 1482 | local void fill_window(s)

and many others like this.